#!/usr/bin/env python3
"""Does the sticky wing actually keep the *combined* book inside the investor
Greek limits — and how, if ever, does it fail?

For each of the four combos already generated by ``theta_engine_v11_gui_runs.py``
(v10-legacy × {RichForce16, Daily15}, v11-new × {RichForce16, Daily15}), this
script re-runs a single-pass replay and — for every bar where the short book
is non-empty — records both:

  * the **short-book-only** check (what the breach would look like with no
    hedge at all — the "naked" counterfactual), and
  * the **full-book** check (shorts + sticky wing + perp — what the strategy
    actually experiences after hedging).

It reports, per combo:
  * % of "live" bars (shorts open) where the FULL book is inside all limits.
  * % of "live" bars that are "naked breaches" — the short book alone is
    breaching AND no wing is currently open to address it.
  * The worst individual lapses (largest post-hedge breach magnitude), with
    date, which Greek(s) are binding, and whether a wing was open at the time.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backtester.core.config import cfg as _cfg
from backtester.core.engine import _inject_indicators, _open_unrealized_pnl
from backtester.core.market_replay import MarketReplay
from backtester.core.portfolio_risk import DEFAULT_INVESTOR_LIMITS, limits_ok
from workspace.strategies.theta_engine._common import BASELINE_DAILY15, BASELINE_RICHFORCE16
from workspace.strategies.theta_engine.v11 import ThetaEngineV11

CAPITAL = float(_cfg.simulation.account_size_usd)
_DISPLAY = {BASELINE_RICHFORCE16: "RichForce16", BASELINE_DAILY15: "Daily15"}


def _base(**overrides: Any) -> Dict[str, Any]:
    g: Dict[str, Any] = {
        "delta": 0.25, "min_dte": 90, "hold_days": 0, "stop_loss_pct": 3.0,
        "take_profit_pct": 0.50, "max_concurrent": 20, "qty_per_1btc_equity": 0.2,
        "launch_accel": 0, "launch_size_mult": 1.0, "greek_limits_mode": "off",
        "perp_delta_hedge": 0, "perp_deadband_pct": 2.0,
        "option_hedge_mode": "sticky_budget", "wing_expiry_mode": "same",
        "wing_delta": 0.10, "wing_trigger": "dg",
        "wing_close_margin_pct": 0.0, "wing_min_hold_minutes": 0.0,
        "wing_cooldown_minutes": 0.0, "wing_cooldown_override_mult": 1.5,
        "wing_side_mode": "count", "wing_delta_mode": "fixed", "wing_delta_ratio": 0.5,
    }
    g.update(overrides)
    return g


def _combo_sets() -> List[Dict[str, Any]]:
    combos = []
    for ep in (BASELINE_RICHFORCE16, BASELINE_DAILY15):
        combos.append(_base(entry_policy=ep, regime="v10_legacy"))
        combos.append(_base(
            entry_policy=ep, regime="v11_new",
            wing_side_mode="greek", wing_delta_mode="relative", wing_delta_ratio=0.5,
            wing_close_margin_pct=3.0, wing_min_hold_minutes=60.0,
            wing_cooldown_minutes=60.0, wing_cooldown_override_mult=1.5,
        ))
    return combos


def _breach_dims(check) -> str:
    dims = []
    if not check.delta_ok:
        dims.append("D")
    if not check.gamma_ok:
        dims.append("G")
    if not check.vega_ok:
        dims.append("V")
    if not check.theta_ok:
        dims.append("T")
    return "".join(dims) or "-"


def _severity(greeks, check) -> float:
    """Worst binding dimension's |value|/band ratio (for ranking lapses)."""
    ratios = []
    if not check.delta_ok and check.delta_band:
        ratios.append(abs(greeks.delta_pct) / check.delta_band)
    if not check.gamma_ok and DEFAULT_INVESTOR_LIMITS.gamma_pct_floor:
        ratios.append(greeks.gamma_pct / DEFAULT_INVESTOR_LIMITS.gamma_pct_floor)
    if not check.vega_ok and DEFAULT_INVESTOR_LIMITS.vega_pct_abs:
        ratios.append(abs(greeks.vega_pct) / DEFAULT_INVESTOR_LIMITS.vega_pct_abs)
    return max(ratios) if ratios else 0.0


def main() -> None:
    date_from, date_to = ThetaEngineV11.DATE_RANGE
    print(f"Loading {date_from} → {date_to}")
    replay = MarketReplay(_cfg.data.options_parquet, _cfg.data.spot_parquet,
                           start=date_from, end=date_to)
    print(f"Intervals: {len(replay._timestamps):,}")

    combo_params = _combo_sets()
    instances = []
    for p in combo_params:
        s = ThetaEngineV11()
        s.configure({k: v for k, v in p.items() if k != "regime"})
        instances.append((p, s))

    _inject_indicators(ThetaEngineV11, [s for _, s in instances], replay, progress=True)

    n = len(instances)
    realized = [0.0] * n
    pos_caches: List[Dict[int, float]] = [{} for _ in range(n)]
    live_bars = [0] * n
    full_ok_bars = [0] * n
    naked_breach_bars = [0] * n
    hedged_breach_bars = [0] * n  # wing open but full book STILL breaching
    worst: List[List[Dict[str, Any]]] = [[] for _ in range(n)]  # top lapses per combo

    t0 = time.time()
    n_states = 0
    last_state = None
    for state in replay:
        n_states += 1
        last_state = state
        for i, (_, strat) in enumerate(instances):
            state.equity_usd = CAPITAL + realized[i]
            open_pnl = _open_unrealized_pnl(strat, state, pos_caches[i])
            perp_pnl = float(strat.perp_mark_pnl(state.spot))
            wing_pnl = float(strat.wing_mark_pnl(state))
            state.nav_usd = state.equity_usd + open_pnl + perp_pnl + wing_pnl

            for trade in strat.on_market_state(state):
                if getattr(trade, "side", "close") == "close":
                    realized[i] += float(trade.pnl)

            n_short = strat.n_short_positions()
            if n_short == 0:
                continue
            live_bars[i] += 1
            has_wing = strat._wing_position() is not None

            short_greeks = strat._shorts_greeks_with_perp(state)
            short_check = limits_ok(short_greeks, DEFAULT_INVESTOR_LIMITS)
            full_greeks = strat._portfolio_greeks_with_overlays(state)
            full_check = limits_ok(full_greeks, DEFAULT_INVESTOR_LIMITS)

            if full_check.ok:
                full_ok_bars[i] += 1
            else:
                if not has_wing:
                    naked_breach_bars[i] += 1
                else:
                    hedged_breach_bars[i] += 1
                sev = _severity(full_greeks, full_check)
                worst[i].append({
                    "dt": state.dt.isoformat(),
                    "sev": round(sev, 2),
                    "dims": _breach_dims(full_check),
                    "delta_pct": round(full_greeks.delta_pct, 2),
                    "gamma_pct": round(full_greeks.gamma_pct, 2),
                    "vega_pct": round(full_greeks.vega_pct, 2),
                    "n_short": n_short,
                    "has_wing": has_wing,
                    "short_only_ok": short_check.ok,
                })
        if n_states % 20000 == 0:
            print(f"  … {n_states} states ({time.time() - t0:.0f}s)")

    if last_state is not None:
        for i, (_, strat) in enumerate(instances):
            for trade in strat.on_end(last_state):
                if getattr(trade, "side", "close") == "close":
                    realized[i] += float(trade.pnl)

    print(f"Done {n_states} states, {n} combos in {time.time() - t0:.1f}s\n")

    header = (
        f"{'regime':<11} {'entry':<12} {'live_bars':>9} {'full_ok_%':>9} "
        f"{'naked_breach_%':>14} {'hedged_breach_%':>15}"
    )
    print(header)
    print("-" * len(header))
    for i, (p, strat) in enumerate(instances):
        lb = live_bars[i] or 1
        print(
            f"{p['regime']:<11} {_DISPLAY.get(p['entry_policy'], p['entry_policy']):<12} "
            f"{live_bars[i]:>9} {100.0*full_ok_bars[i]/lb:>8.2f}% "
            f"{100.0*naked_breach_bars[i]/lb:>13.2f}% {100.0*hedged_breach_bars[i]/lb:>14.2f}%"
        )

    print("\n=== Breach severity distribution (post-hedge, live bars only) ===")
    for i, (p, strat) in enumerate(instances):
        label = f"{p['regime']} / {_DISPLAY.get(p['entry_policy'], p['entry_policy'])}"
        sevs = [r["sev"] for r in worst[i]]
        lb = live_bars[i] or 1
        mild = sum(1 for s in sevs if 0 < s <= 2)
        moderate = sum(1 for s in sevs if 2 < s <= 10)
        severe = sum(1 for s in sevs if s > 10)
        print(
            f"{label:<28} mild(<=2x)={100*mild/lb:5.2f}%  "
            f"moderate(2-10x)={100*moderate/lb:5.2f}%  severe(>10x)={100*severe/lb:5.2f}%  "
            f"max={max(sevs) if sevs else 0:.1f}x"
        )

    print("\n=== Worst 8 lapses per combo (by post-hedge breach severity) ===")
    for i, (p, strat) in enumerate(instances):
        label = f"{p['regime']} / {_DISPLAY.get(p['entry_policy'], p['entry_policy'])}"
        print(f"\n-- {label} --")
        top = sorted(worst[i], key=lambda r: -r["sev"])[:8]
        if not top:
            print("  (none — full book never breached while shorts were open)")
        for r in top:
            print(
                f"  {r['dt']}  sev={r['sev']:.2f}x  dims={r['dims']}  "
                f"D%={r['delta_pct']:+.1f} G%={r['gamma_pct']:+.1f} V%={r['vega_pct']:+.1f}  "
                f"n_short={r['n_short']} wing_open={r['has_wing']} short_alone_ok={r['short_only_ok']}"
            )

    # Cross-check: how did the single worst legacy episode (by date) fare under v11_new?
    print("\n=== Cross-check: legacy's worst-day severity vs v11_new on the same date ===")
    by_label = {
        f"{p['regime']}|{p['entry_policy']}": worst[i] for i, (p, _s) in enumerate(instances)
    }
    for ep in (BASELINE_RICHFORCE16, BASELINE_DAILY15):
        legacy_list = by_label.get(f"v10_legacy|{ep}", [])
        new_list = by_label.get(f"v11_new|{ep}", [])
        if not legacy_list:
            continue
        worst_day = max(legacy_list, key=lambda r: r["sev"])["dt"][:10]
        legacy_day_max = max(
            (r["sev"] for r in legacy_list if r["dt"][:10] == worst_day), default=0.0
        )
        new_day_max = max(
            (r["sev"] for r in new_list if r["dt"][:10] == worst_day), default=0.0
        )
        print(
            f"{_DISPLAY.get(ep, ep):<12} worst_day={worst_day}  "
            f"legacy_max_sev={legacy_day_max:.2f}x  v11_new_max_sev_same_day={new_day_max:.2f}x"
        )


if __name__ == "__main__":
    main()
